only run if there is a pushed gds file, or is manually triggered

diff --git a/.github/workflows/run_verification.yml b/.github/workflows/run_verification.yml
--- a/.github/workflows/run_verification.yml
+++ b/.github/workflows/run_verification.yml
@@ -3,6 +3,8 @@ name: Run Layout Verification
 on:
   workflow_dispatch:
   push:
+    paths:
+      - '**/*.gds'
     branches:
       - main
 
@@ -32,10 +34,10 @@ jobs:
           #locate the .gds file 
           export GDS_FILE=$(find . -type f -name "*.gds" -exec basename {} \; | head -n 1)
 
-          if [[ -z "$GDS_FILE" ]]; then
-            echo "Error: No GDS file provided."
-            exit 78  # Exit with a neutral exit code
-          fi
+          # if [[ -z "$GDS_FILE" ]]; then
+          #   echo "Error: No GDS file provided."
+          #   exit 78  # Exit with a neutral exit code
+          # fi
 
           # print the name of the .gds file
           echo "GDS Files: $GDS_FILE"
